[weapp]
    name = ""
    appId = ""
    appSecret = ""

[mysql]
    driver_name = "mysql"
    data_source_name = "root:123@tcp(localhost:3306)/bastion?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing"
    max_open_conn = 20
    max_idle_conn = 10
    max_conn_life_time = 100

[redis]
    address = ""
    password = ""

[yuque]
    repoID = ""
    token = ""


[aliyunAccessKey]
    AccessKeyId = ""
    AccessKeySecret = ""

