[base]
    env="dev"
    debug_mode="debug"
    time_location="Asia/Shanghai"

[http]
    addr =":8081"                       # 监听地址, default ":8700"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 30                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度

[log]
    log_level = "trace"         #日志打印最低级别

